"""empty message

Revision ID: 26da36a697ca
Revises: 0d26836b15d2
Create Date: 2021-10-21 04:32:50.963610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26da36a697ca'
down_revision = '0d26836b15d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites_people', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favorites_people', 'people_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites_people', 'people_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favorites_people', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
